version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hr_management
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: O9EuyzJ6yfN2g0FLTD5g
      MINIO_ROOT_PASSWORD: rnb30ENe1CVFifTtBhaNXFHM4BuTPLhhUJK05cbl
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
volumes:
  postgres_data:
  minio_data: